##
# Chapter 2
#
# @file
# @version 0.1

CXX = g++
CXXFLAGS = -std=c++23 -fmodules-ts

class_and_structure: class_and_structure.o
	$(CXX) $(CXXFLAGS) class_and_structure.cpp -o class_and_structure.o


# end
