##
# Chapter 1
#
# @file
# @version 0.1

CXX = g++
CXXFLAGS = -std=c++20 -fmodules-ts

hello: hello.o
	$(CXX) hello.cpp -o hello.o

hello_world: hello_world.o
	$(CXX) $(CXXFLAGS) hello_world.cpp -o hello_world.o

square: square.o
	$(CXX) $(CXXFLAGS) square.cpp -o square.o


# end
