##
# Chapter 1
#
# @file
# @version 0.1

CXX = g++
CXXFLAGS = -std=c++23 -fmodules-ts

hello: hello.o
	$(CXX) hello.cpp -o hello.o

hello_world: hello_world.o
	$(CXX) $(CXXFLAGS) hello_world.cpp -o hello_world.o

square: square.o
	$(CXX) $(CXXFLAGS) square.cpp -o square.o

function_overload: function_overloading.o
	$(CXX) $(CXXFLAGS) function_overloading.cpp -o function_overloading.o

initialization: initialization.o
	$(CXX) $(CXXFLAGS) initialization.cpp -o initialization.o

count_occurences: count_occurences.o
	$(CXX) $(CXXFLAGS) count_occurences.cpp -o count_occurences.o



# end
